/** Chat Canvas: classify execution and build iframe srcDoc for web previews. */

const PREVIEW_LANGUAGES = new Set([
  'html',
  'htm',
  'xml',
  'svg',
  'css',
  'javascript',
  'js',
  'typescript',
  'ts',
  'jsx',
  'tsx',
]);

export function extractFirstCodeBlock(text: string): { lang: string; code: string } | null {
  const m = text.match(/```([\w+-]+)?\s*\n([\s\S]*?)```/);
  if (!m) return null;
  const lang = (m[1] || 'text').toLowerCase().trim();
  const code = (m[2] ?? '').trim();
  if (!code) return null;
  return { lang, code };
}

export function getCanvasExecutionMode(lang: string): 'preview' | 'terminal' {
  const l = lang.toLowerCase().trim();
  return PREVIEW_LANGUAGES.has(l) ? 'preview' : 'terminal';
}

/** Build a full HTML document for the live preview iframe (web / apps only). */
export function buildPreviewSrcDoc(code: string, lang: string): string {
  const l = lang.toLowerCase();
  const forwardErrors = `<script>(function(){function f(m){try{parent.postMessage({type:'preview_error',error:String(m)},'*');}catch(e){}}window.addEventListener('error',function(e){f(e.message||e.error&&e.error.message||'Error');});window.addEventListener('unhandledrejection',function(e){f((e.reason&&e.reason.message)||e.reason||'Unhandled rejection');});})();</script>`;
  // Hide the verbose “mission checklist / Instruction:” overlay sometimes generated by canvas games.
  // Keep it conservative: we only hide small text nodes themselves (not parent layout),
  // to avoid blanking the whole canvas.
  const hudSanitizer = `<script>(function(){
    try{
      var phrases=[
        'implement gravity and friction constants',
        'design multi-tier level layout',
        'integrate real-time hud with dom synchronization',
        'establish collision-based damage triggers',
        'move with a/d and jump with space',
        'collect the yellow data fragments',
        'avoid falling into the void'
      ];
      var instrRe=/^\\s*instruction\\s*:/i;
      function norm(s){
        return String(s||'')
          .toLowerCase()
          .replace(/[^a-z0-9]+/g,' ')
          .trim();
      }
      var normPhrases=phrases.map(norm).filter(Boolean);
      function allowedTag(tag){
        tag=String(tag||'').toUpperCase();
        return tag==='P' || tag==='SPAN' || tag==='DIV' || tag==='LI' || tag==='H1' || tag==='H2' || tag==='H3' || tag==='H4' || tag==='H5' || tag==='H6';
      }
      function hideNode(n){
        try{ n.style.display='none'; }catch(_){}
      }
      function shouldSkipBySize(n){
        try{
          var r=n.getBoundingClientRect();
          // If this looks like a large container, don't hide it (prevents blank canvas).
          if(r && r.height && r.height>70) return true;
        }catch(_){}
        return false;
      }
      function run(){
        var nodes=document.querySelectorAll('*');
        for(var i=0;i<nodes.length;i++){
          var n=nodes[i];
          if(!n || !n.textContent) continue;
          var t=String(n.textContent||'').trim();
          if(!t) continue;
          if(!allowedTag(n.tagName)) continue;
          if(shouldSkipBySize(n)) continue;

          if(instrRe.test(t)){
            hideNode(n);
            continue;
          }

          var nt=norm(t);
          for(var p=0;p<normPhrases.length;p++){
            var ph=normPhrases[p];
            if(ph && nt.indexOf(ph)!==-1){
              hideNode(n);
              break;
            }
          }
        }
      }
      run();
      setTimeout(run, 250);
    }catch(e){}
  })();</script>`;

  if (l === 'html' || l === 'htm') {
    let doc = code;
    if (!/cdn\.tailwindcss\.com/i.test(doc) && /<head[\s>]/i.test(doc)) {
      doc = doc.replace(/<head([^>]*)>/i, '<head$1><script src="https://cdn.tailwindcss.com"></script>');
    } else if (!/cdn\.tailwindcss\.com/i.test(doc) && !/<!DOCTYPE/i.test(doc)) {
      doc = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.tailwindcss.com"></script></head><body>${doc}</body></html>`;
    }
    if (/<\/body>/i.test(doc)) {
      return doc.replace(/<\/body>/i, `${hudSanitizer}${forwardErrors}</body>`);
    }
    return doc + hudSanitizer + forwardErrors;
  }

  if (l === 'xml' || l === 'svg') {
    return `${code}${hudSanitizer}${forwardErrors}`;
  }

  if (l === 'css') {
    return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.tailwindcss.com"></script><style>${code}</style>${hudSanitizer}${forwardErrors}</head><body></body></html>`;
  }

  if (l === 'javascript' || l === 'js') {
    const srcJs = JSON.stringify(code);
    return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.tailwindcss.com"></script>${forwardErrors}</head><body><div id="root"></div><script>try{eval(${srcJs});}catch(e){parent.postMessage({type:'preview_error',error:String(e&&e.message||e)},'*');}</script>${hudSanitizer}</body></html>`;
  }

  if (l === 'typescript' || l === 'ts' || l === 'tsx' || l === 'jsx') {
    const src = code.replace(/export\s+default\s+/g, '');
    const userSrcJson = JSON.stringify(src);
    return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><script src="https://cdn.tailwindcss.com"></script><script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script><script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script><script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>${forwardErrors}</head><body><div id="root"></div><script>(function(){try{var userSrc=${userSrcJson};var out=Babel.transform(userSrc,{presets:[['react',{runtime:'classic'}],'typescript'],filename:'app.tsx'}).code;var module={exports:{}};var exports=module.exports;var React=window.React;var ReactDOM=window.ReactDOM;eval(out);var C=module.exports.default||module.exports.App||(typeof App!=='undefined'?App:null);var el=document.getElementById('root');if(C&&el){if(ReactDOM.createRoot){ReactDOM.createRoot(el).render(React.createElement(C));}else{ReactDOM.render(React.createElement(C),el);}}}catch(e){parent.postMessage({type:'preview_error',error:String(e&&e.message||e)},'*');}})();</script>${hudSanitizer}</body></html>`;
  }

  return `${code}${hudSanitizer}${forwardErrors}`;
}
